version: "3.7"

services:
  webclient-dev:
    container_name: musicthing-webclient-dev
    build:
      context: ./webclient/.
      dockerfile: dev.dockerfile
    volumes:
      - "./webclient:/app"
      - "/app/node_modules"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

  backend-dev:
    container_name: musicthing-backend-dev
    build:
      context: ./backend/.
      dockerfile: dev.dockerfile
    volumes:
      - "./testmusic:/testmusic"
      - "./backend:/app"
      - "/app/node_modules"
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=development
